bc:
  conf.version: 0.0.0

---
spring.profiles: party
bc.application.party: true

---
spring profiles: secure
bc.application.secure: true

---
spring profiles: secure,party
bc.application:
  party: true
  secure: true
  privateParty: true
